services:
  symfony:
    image: symfony-${PROJECT_NAME}:latest 
    build:
      context: . 
      dockerfile: ./infrastructure/php/Dockerfile
      args:
        VERSION: latest
    container_name: symfony-${PROJECT_NAME}
    volumes:
      - ./api:/var/www
      - ./infrastructure/php/php.ini:/usr/local/etc/php/conf.d/docker-php-config.ini
      - ./infrastructure/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    command: ["php-fpm"]
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD-SHELL", "php-fpm -t || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    networks:
      - app-products

  react:
    image: react-${PROJECT_NAME}:latest
    build:
      context: . 
      dockerfile: ./infrastructure/node/Dockerfile
      args:
        VERSION: latest
    container_name: react-${PROJECT_NAME}
    volumes:
      - ./frontend:/var/www
    ports:
      - "4000:3000"
    healthcheck:
      test: ["CMD-SHELL", "pgrep npm || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    networks:
      - app-products

  nginx:
    image: nginx:alpine
    container_name: nginx-${PROJECT_NAME}
    volumes:
      - ./infrastructure/nginx/backend.conf:/etc/nginx/conf.d/backend.conf
      - ./infrastructure/nginx/frontend.conf:/etc/nginx/conf.d/frontend.conf
      - ./api:/var/www
    ports:
      - "8800:80"
    depends_on:
      symfony:
        condition: service_healthy
      react:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-products

  mysql:
    image: mysql:8.0
    container_name: mysql-${PROJECT_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - app-products

  mail:
    container_name: mail-${PROJECT_NAME}
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "1025:1025"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-products

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbitmq
    container_name: rabbitmq-${PROJECT_NAME}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./infrastructure/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      symfony:
        condition: service_healthy
    networks:
      - app-products

  redis:
    container_name: redis-${PROJECT_NAME}
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./infrastructure/redis/data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app-products

  supervisor:
    image: supervisor-${PROJECT_NAME}:latest
    container_name: supervisor-${PROJECT_NAME}
    build:
      context: .
      dockerfile: ./infrastructure/supervisor/Dockerfile
      args:
        VERSION: latest
    volumes:
      - ./api:/var/www
      - ./infrastructure/supervisor/supervisord.conf:/etc/supervisor/supervisord.conf
    ports:
      - "9001:9001"  
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
    healthcheck:
      test: ["CMD-SHELL", "supervisorctl status || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      symfony:
        condition: service_healthy
    networks:
      - app-products

networks:
  app-products:
    driver: bridge

