doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        types:
            uuid_value_object: App\Shared\Infrastructure\Persistence\Doctrine\Types\UuidValueObjectType
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '16'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        controller_resolver: 
            auto_mapping: false
        mappings:
            User:
                type: xml     
                is_bundle: false
                dir: '%kernel.project_dir%/src/User/Infrastructure/Mapping/Doctrine'
                prefix: 'App\User\Domain\Entity'
                alias: User
            Product:
                type: xml     
                is_bundle: false
                dir: '%kernel.project_dir%/src/Product/Infrastructure/Mapping/Doctrine'
                prefix: 'App\Product\Domain\Entity'
                alias: Product

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
