nelmio_api_doc:
    documentation:
        info:
            title: 'Products API'
            description: 'API documentation for products'
            version: '1.0.0'
        paths:
            /api/login_check:
                post:
                    summary: 'Login user'
                    description: 'Authenticates a user and returns a JWT token'
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    required:
                                        - email
                                        - password
                                    properties:
                                        email:
                                            type: string
                                            format: email
                                            example: 'admin@example.com'
                                        password:
                                            type: string
                                            format: password
                                            example: 'administrator'
                    responses:
                        '200':
                            description: 'Successful response'
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                                example: 'eyJhbGciOiJIUzI1NiIsInR5...'
                        '401':
                            description: 'Unauthorized'
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            message:
                                                type: string
                                                example: 'Invalid email or password'
        components:
            securitySchemes:
                BearerAuth:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - BearerAuth: [] 
    areas:
        default:
            path_patterns:
                - '^/api(?!/doc$)'
