version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - "8780:80"
    volumes:
      - .:/var/www
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=blog-db
    depends_on:
      - db
      - rabbitmq

  db:
    image: mysql:8.0
    container_name: blog
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog-db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blog_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "8081:80"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672"  
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest